name: CI testing

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.7
    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}

    - name: Build
      run: |
          ls
          printenv | grep -i go
          go version
          pwd
          make style test
